---

- name: Shibboleth SP | add idp metadata
  template: 
    src: " {{ item.src }} "
    dest: " {{ item.dir }}/{{ item.name }} "
    owner: " {{ item.user }} "
    group: " {{ item.group }}"
  notify: restart shibd
  with_items:
  - idp_metadata