---
# tasks file for shibboleth-sp

- include_tasks: install.yml

- include_tasks: configuration.yml

- include_tasks: certificates.yml
  when: shibbolethsp_with_certificates | bool

- include_tasks: apache_reverse_proxy.yml
  when: shibbolethsp_with_apache | bool

- include_tasks: idp_configuration.yml
  when: shibbolethsp_idp_configuration | bool