---
# handlers file for shibboleth-sp

- name: restart shibd
  service:
    name: shibd
    state: restarted

- name: apache2 restart
  service:
    name: apache2
    enabled: yes
    state: restarted